// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLotCfyz4liIid8oQBLGtly_N_V52txdM',
    appId: '1:136060280282:web:7598bc3d3298b5dc38b4e3',
    messagingSenderId: '136060280282',
    projectId: 'navix-a4375',
    authDomain: 'navix-a4375.firebaseapp.com',
    storageBucket: 'navix-a4375.firebasestorage.app',
    measurementId: 'G-0F2CFVH5YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_58JpnRK5qPqVJQnsRo82cURHYXnNiM',
    appId: '1:136060280282:android:84f5f0be0291cbf938b4e3',
    messagingSenderId: '136060280282',
    projectId: 'navix-a4375',
    storageBucket: 'navix-a4375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGvc0s3ZGVR9PPPESXnkqylvwEDCQD5M',
    appId: '1:136060280282:ios:b007c5b942c14e7638b4e3',
    messagingSenderId: '136060280282',
    projectId: 'navix-a4375',
    storageBucket: 'navix-a4375.firebasestorage.app',
    iosBundleId: 'com.aw.navix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzGvc0s3ZGVR9PPPESXnkqylvwEDCQD5M',
    appId: '1:136060280282:ios:b007c5b942c14e7638b4e3',
    messagingSenderId: '136060280282',
    projectId: 'navix-a4375',
    storageBucket: 'navix-a4375.firebasestorage.app',
    iosBundleId: 'com.aw.navix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLotCfyz4liIid8oQBLGtly_N_V52txdM',
    appId: '1:136060280282:web:53d6018b73177ae938b4e3',
    messagingSenderId: '136060280282',
    projectId: 'navix-a4375',
    authDomain: 'navix-a4375.firebaseapp.com',
    storageBucket: 'navix-a4375.firebasestorage.app',
    measurementId: 'G-14QVLMNW41',
  );
}
